name: Compile production files

on:
  workflow_dispatch:
  push:


jobs:

  compile-production-files:
    runs-on: ubuntu-latest
    # needs: esphome-firmware-validation

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Generate full documentation
        uses: INTI-CMNB/KiBot@v2_k7
        env:
          MOUSER_KEY: ${{ secrets.MOUSER_KEY }}
          NEXAR_CLIENT_ID: ${{ secrets.NEXAR_CLIENT_ID }}
          NEXAR_CLIENT_SECRET: ${{ secrets.NEXAR_CLIENT_SECRET }}
          TME_TOKEN: ${{ secrets.TME_TOKEN }}
          TME_APP_SECRET: ${{ secrets.TME_APP_SECRET }}
        with:
          dir: .
          config: .kibot/full-outputs.kibot.yaml
          schema: electronics/electronics.kicad_sch
          board: electronics/electronics.kicad_pcb
          install3D: yes

      - name: Fix file permissions for generated files
        run: sudo chown -R $(id -u):$(id -g) ./exports

      - name: Get current date and time
        id: gitstamp
        run: echo "datehash=$(git log -1 --format='%as')-$(git log -1 --pretty=format:%h)" >> $GITHUB_OUTPUT

      # - name: Commit renders to generated folder
      #   run: |
      #     mkdir -p generated/images/
      #     cp -r exports/renders/*.png generated/images/
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add -f generated/images
      #     git commit -m "latest renders"
      #     git push

      - name: Archive project artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electronics-${{ steps.gitstamp.outputs.datehash }}
          if-no-files-found: error
          path: |

            # Documentations
            exports/electronics-schematic-*.pdf
            exports/electronics-pcb-layers-*.pdf
            exports/electronics-pcb-layers-*.pdf
            exports/electronics-design-report-*.txt

            exports/datasheets
            exports/electronics-ibom-*.html
            exports/electronics-*.csv
            exports/electronics-*.xlsx

            # Production files
            exports/electronics-gerbers-*.zip
            exports/electronics-bom-*.csv

            ## Extras
            exports/renders/*.png
            exports/renders/*.jpg
            exports/electronics-*.step
            exports/project
